academy:

  replicaCount: 5

  image:
    repository: ${deployment_image}
    pullPolicy: IfNotPresent

  serviceAccountName: ${service_account}
  service:
    type: ClusterIP
    port: 80

mysql:

  image:
    repository: fsadykov/centos_mysql
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306
    serviceName: academy-mysql-service

nameOverride: ""
fullnameOverride: ""


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - ${deployment_endpoint}
  tls:
   - secretName: academy-chart-tls
     hosts:
       - ${deployment_endpoint}

globalEnvironments:
  enabled: true
  environments:

  - name: MYSQL_USER
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: mysql_user
    
  - name: MYSQL_DATABASE
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: mysql_database
      
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: mysql_password
   
  - name: ADMIN_USER
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: admin_user
    

  - name: ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: admin_password
    
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: mysql_root_password
    

  - name: APPLICATION_ENDPOINT
    value: ${deployment_endpoint}

  - name: GIT_TOKEN
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: github_token
    
  - name: SOCIAL_AUTH_GITHUB_KEY
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: github_client_id
    
  - name: SOCIAL_AUTH_GITHUB_SECRET
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: github_client_secret

  - name: SOCIAL_AUTH_GITHUB_SECRET
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: github_client_secret
  
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: application_secret


  - name: VIMEO_ACCESS_TOKEN
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: vimeo_access_token

  - name: VIMEO_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: vimeo_client_id
  
  - name: VIMEO_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: ${academy_credentials}
        key: vimeo_client_secret


imageSecret:
  enabled: true
  allSecrets:
  - name: nexus-creds

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
