apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.serviceName }}
  labels:
    app.kubernetes.io/name: {{ include "academy.name" . }}-mysql
    helm.sh/chart: {{ include "academy.chart" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}-mysql
    app.kubernetes.io/managed-by: {{ .Release.Service }}-mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: {{ include "academy.name" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}-mysql
